name: aad_oauth
description: A Flutter OAuth package for performing user authentication against
  Azure Active Directory OAuth2 v2.0 endpoint.
version: 1.0.0
homepage: https://github.com/Earlybyte/aad_oauth

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: 
  webview_flutter:
  js:
  http:
  shared_preferences:
  dartz:
  equatable:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
  - assets/msalv2.js
